apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conproxy.fullname" . }}
  labels:
    {{- include "conproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "conproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "conproxy.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      hostAliases:
        - hostnames:
            - host.docker.internal
          ip: {{ .Values.hostIP | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: CONPROXY_CONFIG
              value: /etc/conproxy/conproxy.toml
            - name: RUST_LOG
              value: info
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/conproxy
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "conproxy.fullname" . }}
        - name: tmp
          emptyDir: {}
